# Generated by Django 6.1 on 2026-08-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('evaluation_type', models.CharField(max_length=20)),
                ('expected_behaviour', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Llm_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.attack')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.llm_model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_response', models.TextField()),
                ('response_time_ms', models.IntegerField()),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tester.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('report_path', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tester.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('verdict', models.CharField(max_length=20)),
                ('evidence_summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tester.testrun')),
            ],
        ),
    ]
