# Generated by Django 6.1 on 2026-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='attack_id',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
