# Generated by Django 6.1 on 2026-08-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_remove_attack_evaluation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrun',
            old_name='attack_id',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='user_id',
            new_name='user',
        ),
    ]
