# Generated by Django 6.1 on 2026-08-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_rename_attack_id_testrun_attack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('ground_truth_label', models.CharField(blank=True, max_length=20)),
                ('split', models.CharField(default='train', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('engine_prediction', models.CharField(blank=True, max_length=20, null=True)),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.attack')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.llm_model')),
            ],
        ),
    ]
